### ISSUE TITLE
VS Code: Add a Rmarkdown Code Chunk Snippet Key Binding

### ISSUE THREAD

**Issue by ratnanil** [mschmidty/schmidty_notes#1]
Love your blog! Quick question concerning your blog post: https://www.schmidtynotes.com/blog/r/2021-09-28-vscode-rmd-code-chunk-snippet/

Shoudn't it be:

```diff
[
  {
-    "key": "cmd+alt+i",
+    "key": "ctrl+alt+i",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
-    "args": {"snippet": "```r\n$0\n```"}
+    "args": {"snippet": "```{r}\n$0\n```"}
  },
]
```

**Comment by mschmidty** [comment]
Yes to the `{r}`.  Thank you for the careful read. I fixed it.  I'm going to leave the `cmd` because I use a mac. But I added a note for windows users.
